services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
      - db:/var/lib/postgresql/data
   
  app: 
    container_name: brev.ly.server
    depends_on:
      - postgresql
    build: .
    ports:
      - 3000:$PORT
    restart: unless-stopped
    environment:
      - PORT=$PORT
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - DATABASE_URL=$DATABASE_URL_DOCKER
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL

networks:
  app:
    driver: bridge
  db:
    driver: bridge

volumes:
  db:
  